# Generated by Django 6.0.4 on 2026-04-28 12:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('PROFESSIONAL', 'Professional Elective'), ('OPEN', 'Open Elective'), ('ABILITY', 'Ability Enhancement')], max_length=20)),
                ('job_perspective', models.TextField()),
                ('salient_features', models.TextField(blank=True)),
                ('prerequisites', models.TextField(blank=True, default='None')),
                ('is_open_elective', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('current_seats', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='electives.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField(default=7.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('semester', models.PositiveIntegerField(default=6)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('usn', models.CharField(blank=True, max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllocationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_rank', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='electives.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_result', to='electives.student')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ALLOCATED', 'Allocated'), ('WAITLISTED', 'Waitlisted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='electives.student')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='StudentCourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=20)),
                ('is_future', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='electives.student')),
            ],
            options={
                'unique_together': {('student', 'course_code')},
            },
        ),
    ]
